export type ScholarshipStatus = "Open" | "Closing soon" | "Coming soon";

export type Scholarship = {
  id: string;
  name: string;
  country: "Italy" | "France" | "Germany" | "Türkiye" | "China";
  flag: string;
  provider: string;
  levels: string[];
  fundingType: "Fully funded" | "Tuition + stipend" | "Tuition waiver" | "Needs-based";
  status: ScholarshipStatus;
  deadlineLabel: string;
  deadlineISO?: string;
  intake: string;
  summary: string;
  eligibility: string[];
  documents: string[];
  benefits: string[];
  steps: string[];
  officialUrl: string;
  sourceLabel: string;
  note?: string;
};

export const scholarshipCountries = [
  { name: "Italy", code: "IT", flag: "/polaris/flags/it.png" },
  { name: "France", code: "FR", flag: "/polaris/flags/fr.png" },
  { name: "Germany", code: "DE", flag: "/polaris/flags/de.png" },
  { name: "Türkiye", code: "TR", flag: "/polaris/flags/tr.png" },
  { name: "China", code: "CN", flag: "/polaris/flags/cn.png" },
] as const;

const flags = Object.fromEntries(scholarshipCountries.map((country) => [country.name, country.flag]));

export const scholarships: Scholarship[] = [
  {
    id: "it-ergo-2026",
    name: "ER.GO Scholarship 2026/27",
    country: "Italy",
    flag: flags.Italy,
    provider: "ER.GO Emilia-Romagna",
    levels: ["Bachelor's", "Master's", "PhD"],
    fundingType: "Needs-based",
    status: "Closing soon",
    deadlineLabel: "24 August 2026 · 16:00 Italy time",
    deadlineISO: "2026-08-24",
    intake: "2026/27",
    summary: "Regional right-to-study support for eligible students enrolled at institutions in Emilia-Romagna.",
    eligibility: [
      "Meet the call's economic and merit thresholds",
      "Enrol, or intend to enrol, at an eligible Emilia-Romagna institution",
      "International applicants must document household income and assets",
    ],
    documents: [
      "Identity document and enrolment/application details",
      "Household composition, 2025 gross income and asset evidence",
      "Foreign documents translated and legalised where required",
      "Domicile or rental evidence when applying as a non-resident student",
    ],
    benefits: [
      "Cash award based on ISEE/economic band and residence status",
      "Regional tax and tuition-fee benefits under the call",
      "Possible catering and accommodation-related support",
    ],
    steps: ["Create/access your ER.GO account", "Complete the benefits application", "Upload or submit required economic documents", "Track rankings and any correction deadlines"],
    officialUrl: "https://www.er-go.it/international-students/benefits/focus-on-scholarship",
    sourceLabel: "ER.GO official benefits portal",
    note: "The complete 2026/27 call controls all income, merit and document rules.",
  },
  {
    id: "it-edisu-2026",
    name: "EDISU Piemonte Scholarship 2026/27",
    country: "Italy",
    flag: flags.Italy,
    provider: "EDISU Piemonte",
    levels: ["Bachelor's", "Master's", "PhD"],
    fundingType: "Needs-based",
    status: "Open",
    deadlineLabel: "4 September 2026 · 12:00 Italy time",
    deadlineISO: "2026-09-04",
    intake: "2026/27",
    summary: "Financial support and related student benefits for eligible learners studying in Piedmont.",
    eligibility: ["Enrolment in an eligible Piedmont institution", "Economic and asset limits in the current call", "Merit requirements based on year and programme"],
    documents: ["Identity and programme details", "Family income and asset documents", "Translated/legalised foreign economic documents", "Temporary Access Code or Italian digital identity as applicable"],
    benefits: ["Scholarship amount linked to financial and residence status", "Possible accommodation and meal-service benefits", "Tuition and regional-tax relief subject to the call"],
    steps: ["Review the 2026/27 notice", "Access the EDISU online procedure", "Submit benefits application by the main student deadline", "Check provisional and final rankings"],
    officialUrl: "https://www.edisu.piemonte.it/en/news/notices/benefits-application-202627-publication-notice-competition-and-start-procedure",
    sourceLabel: "EDISU Piemonte official notice",
  },
  {
    id: "it-maeci-next",
    name: "MAECI Grants for Foreign Students",
    country: "Italy",
    flag: flags.Italy,
    provider: "Italian Ministry of Foreign Affairs",
    levels: ["Master's", "PhD", "Research", "Language"],
    fundingType: "Tuition + stipend",
    status: "Coming soon",
    deadlineLabel: "2027/28 call not yet announced",
    intake: "2027/28 expected",
    summary: "Italian-government grants for eligible foreign citizens pursuing approved study or research routes in Italy.",
    eligibility: ["Citizenship and age rules depend on the annual call", "Admission or intended admission to an eligible course", "Academic and language requirements for the selected route"],
    documents: ["Passport or national ID", "Degree certificates and transcripts", "Language certificate where required", "CV, study/research information and any call-specific declarations"],
    benefits: ["Periodic grant according to the annual call", "Health and accident insurance during the grant period", "Tuition treatment subject to institution and call rules"],
    steps: ["Check country eligibility in the new call", "Select an eligible course", "Prepare academic and language evidence", "Apply through the Study in Italy portal"],
    officialUrl: "https://www.esteri.it/en/servizi-opportunita/opportunita/borse-di-studio/per-cittadini-stranieri/borsestudio_stranieri/",
    sourceLabel: "Italian Ministry of Foreign Affairs",
    note: "The 2026/27 deadline was 26 March 2026. Wait for the official 2027/28 call before relying on dates or benefits.",
  },
  {
    id: "it-padua-next",
    name: "Padua International Excellence Scholarship",
    country: "Italy",
    flag: flags.Italy,
    provider: "University of Padua",
    levels: ["Bachelor's", "Master's"],
    fundingType: "Tuition + stipend",
    status: "Coming soon",
    deadlineLabel: "Next admission cycle to be announced",
    intake: "2027/28 expected",
    summary: "Highly selective awards for talented international students applying to English-taught degrees at Padua.",
    eligibility: ["International applicant with a foreign entry qualification", "Application to an eligible English-taught degree", "Strong academic record; selection is competitive"],
    documents: ["Degree-programme application", "Previous qualification and transcripts", "Identity and language evidence", "Any programme-specific documents"],
    benefits: ["€8,000 gross per academic year under the published programme", "Tuition-fee exemption", "Award duration follows the current programme rules"],
    steps: ["Choose an eligible English-taught degree", "Submit the degree application by its deadline", "No separate scholarship form where automatic consideration applies", "Monitor admission and scholarship results"],
    officialUrl: "https://www.unipd.it/en/padua-international-excellence-scholarship-programme",
    sourceLabel: "University of Padua",
  },

  {
    id: "fr-eiffel-next",
    name: "France Excellence Eiffel Scholarship",
    country: "France",
    flag: flags.France,
    provider: "French Ministry for Europe and Foreign Affairs",
    levels: ["Master's", "PhD"],
    fundingType: "Fully funded",
    status: "Coming soon",
    deadlineLabel: "2027 call not yet announced",
    intake: "2027/28 expected",
    summary: "Prestigious French-government funding for high-achieving international Master’s and doctoral candidates nominated by a French institution.",
    eligibility: ["International candidate within the annual age and nationality rules", "Eligible Master’s/engineering or doctoral route", "Nomination must be submitted by a French higher-education institution"],
    documents: ["CV and academic transcripts", "Degree certificates and ranking evidence", "Study or research project", "Language and institution-requested supporting documents"],
    benefits: ["Monthly allowance under the current call", "International and national travel support where applicable", "Insurance, activities and possible housing assistance"],
    steps: ["Identify an eligible French programme", "Ask the institution about Eiffel nomination", "Provide its internal nomination documents", "Institution submits the final Campus France application"],
    officialUrl: "https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program",
    sourceLabel: "Campus France",
    note: "Students cannot submit directly to Campus France; the French institution nominates the candidate.",
  },
  {
    id: "fr-saclay-next",
    name: "Université Paris-Saclay International Master's Scholarship",
    country: "France",
    flag: flags.France,
    provider: "Université Paris-Saclay",
    levels: ["Master's"],
    fundingType: "Tuition + stipend",
    status: "Coming soon",
    deadlineLabel: "2027 cycle not yet announced",
    intake: "2027/28 expected",
    summary: "Competitive support for selected international students admitted to eligible Paris-Saclay Master’s programmes.",
    eligibility: ["First admission to an eligible Paris-Saclay Master’s programme", "International status and age/registration rules in the call", "Selection for the scholarship application by the programme team"],
    documents: ["Completed Master’s admission file", "Academic records and degree evidence", "CV and motivation material", "Referees or other scholarship documents when invited"],
    benefits: ["€10,000 per year under the published scheme", "Up to €900 for travel and visa expenses", "Award normally follows the eligible Master’s year"],
    steps: ["Apply to an eligible Master’s programme", "Wait for programme admission and scholarship pre-selection", "Complete the invited scholarship form", "Ensure referees submit any requested material"],
    officialUrl: "https://www.universite-paris-saclay.fr/en/admission/bourses-et-aides-financieres/international-masters-scholarships-program",
    sourceLabel: "Université Paris-Saclay",
  },
  {
    id: "fr-boutmy-next",
    name: "Émile Boutmy Scholarship",
    country: "France",
    flag: flags.France,
    provider: "Sciences Po",
    levels: ["Bachelor's", "Master's"],
    fundingType: "Tuition waiver",
    status: "Coming soon",
    deadlineLabel: "2027 admissions open from September 2026",
    intake: "2027/28",
    summary: "Merit- and profile-based tuition support for eligible first-time non-EU applicants to Sciences Po.",
    eligibility: ["First-time applicant from a non-European Union state", "Household is not an EU tax filer", "Admission through an eligible undergraduate or Master’s route"],
    documents: ["Sciences Po admission application", "Academic transcripts and qualifications", "Financial information requested for scholarship assessment", "Scholarship request within the application where required"],
    benefits: ["Undergraduate or Master’s tuition grant according to the award decision", "Renewal subject to academic and programme conditions"],
    steps: ["Select the correct international admissions route", "Request Boutmy consideration inside the degree application", "Upload all financial and academic evidence", "Submit by the relevant admission deadline"],
    officialUrl: "https://www.sciencespo.fr/students/en/fees-funding/bursaries-financial-aid/emile-boutmy-scholarship/",
    sourceLabel: "Sciences Po",
  },
  {
    id: "fr-ens-next",
    name: "ENS International Selection",
    country: "France",
    flag: flags.France,
    provider: "École normale supérieure (PSL)",
    levels: ["Master's"],
    fundingType: "Fully funded",
    status: "Coming soon",
    deadlineLabel: "2027 dates to be announced",
    intake: "2027/28 expected",
    summary: "Selective Arts & Humanities and Sciences routes combining ENS training with multi-year scholarship support.",
    eligibility: ["International applicant meeting the study-history rules", "Strong academic profile in an eligible Arts/Humanities or Science field", "Availability for written/oral selection stages"],
    documents: ["High-school diploma and university transcripts", "CV and motivation letter", "Study or research project where required", "Two to four academic recommendation letters"],
    benefits: ["Monthly scholarship under the current selection rules", "ENS academic training and student support", "Access to the ENS/PSL academic environment"],
    steps: ["Choose Arts & Humanities or Sciences selection", "Prepare the online application and references", "Submit within the discipline window", "Complete remote/on-site selection if shortlisted"],
    officialUrl: "https://www.ens.psl.eu/en/une-formation-d-exception/admissions/international/international-selection",
    sourceLabel: "École normale supérieure",
  },

  {
    id: "de-epos-open",
    name: "DAAD EPOS Scholarships",
    country: "Germany",
    flag: flags.Germany,
    provider: "German Academic Exchange Service (DAAD)",
    levels: ["Master's", "PhD"],
    fundingType: "Fully funded",
    status: "Open",
    deadlineLabel: "Varies by selected course for 2027/28",
    intake: "2027/28",
    summary: "Development-related postgraduate scholarships for qualified professionals from eligible developing and newly industrialised countries.",
    eligibility: ["Graduate from an eligible country", "Normally at least two years of relevant professional experience", "Academic qualifications and motivation connected to development impact"],
    documents: ["DAAD application form and CV", "Motivation letter", "Degrees, transcripts and employment certificates", "Language proof and course-specific documents"],
    benefits: ["Monthly scholarship payment", "Insurance and travel allowance", "Possible rent, family and preparatory German-language support"],
    steps: ["Use the EPOS course list", "Check the exact programme deadline", "Prepare DAAD and university documents", "Apply through the route specified by that programme"],
    officialUrl: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50076777",
    sourceLabel: "DAAD Scholarship Database",
    note: "Each EPOS programme has its own deadline and sometimes its own application route.",
  },
  {
    id: "de-all-disciplines-open",
    name: "DAAD Study Scholarships – Master's Studies",
    country: "Germany",
    flag: flags.Germany,
    provider: "German Academic Exchange Service (DAAD)",
    levels: ["Master's"],
    fundingType: "Fully funded",
    status: "Open",
    deadlineLabel: "Applications from 1 June; country deadline varies",
    intake: "2027/28",
    summary: "DAAD funding for international graduates completing a full postgraduate or Master’s degree in Germany.",
    eligibility: ["Recognised first degree completed by the relevant start date", "Strong academic record and convincing study plan", "Country-specific time-since-degree and language conditions"],
    documents: ["DAAD portal application", "CV and motivation letter", "Degree certificates and transcripts", "Language proof and admission-related documents"],
    benefits: ["Monthly scholarship payment", "Travel and insurance support", "Possible study allowance and other personal circumstances support"],
    steps: ["Open the DAAD listing for your country", "Check your exact deadline and eligible fields", "Prepare portal documents", "Apply to DAAD and universities as instructed"],
    officialUrl: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50026200",
    sourceLabel: "DAAD Scholarship Database",
  },
  {
    id: "de-boell-2026",
    name: "Heinrich Böll Foundation Scholarship",
    country: "Germany",
    flag: flags.Germany,
    provider: "Heinrich Böll Foundation",
    levels: ["Master's", "PhD"],
    fundingType: "Fully funded",
    status: "Open",
    deadlineLabel: "1 September 2026",
    deadlineISO: "2026-09-01",
    intake: "Autumn 2026 round",
    summary: "Scholarships for academically strong, socially engaged graduate and doctoral applicants aligned with the foundation's values.",
    eligibility: ["Very good academic record", "Demonstrated social or political engagement", "International graduate/doctoral applicants need the specified German proficiency"],
    documents: ["Online application and personal information", "Academic certificates and transcripts", "Motivation/profile evidence", "Language proof and references as requested"],
    benefits: ["Monthly scholarship according to programme category", "Academic and professional development activities", "Network and mentoring opportunities"],
    steps: ["Check the international applicant category", "Complete the online application", "Upload academic, language and engagement evidence", "Participate in later selection stages if invited"],
    officialUrl: "https://www.boell.de/en/applying-scholarship",
    sourceLabel: "Heinrich Böll Foundation",
  },
  {
    id: "de-helmut-next",
    name: "DAAD Helmut-Schmidt-Programme",
    country: "Germany",
    flag: flags.Germany,
    provider: "German Academic Exchange Service (DAAD)",
    levels: ["Master's"],
    fundingType: "Fully funded",
    status: "Coming soon",
    deadlineLabel: "Annual window usually 1 June–31 July; verify next call",
    intake: "Next cycle",
    summary: "Scholarship for selected public policy, governance, development and social-science Master’s programmes.",
    eligibility: ["Graduate from an eligible developing or emerging country", "Relevant academic background", "Convincing commitment to public-interest development and social impact"],
    documents: ["DAAD application form", "Single motivation letter addressing chosen programmes", "CV, degrees and transcripts", "Language, employment and reference evidence where requested"],
    benefits: ["Monthly DAAD scholarship", "Insurance and travel allowance", "Mandatory German course before study", "Possible study/research and family-related support"],
    steps: ["Review participating Master’s programmes", "Choose up to the permitted number", "Apply directly to the selected programme(s)", "Follow programme and DAAD selection communications"],
    officialUrl: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/?detail=50026397",
    sourceLabel: "DAAD Scholarship Database",
  },

  {
    id: "tr-turkiye-next",
    name: "Türkiye Scholarships",
    country: "Türkiye",
    flag: flags.Türkiye,
    provider: "Presidency for Turks Abroad and Related Communities (YTB)",
    levels: ["Associate", "Bachelor's", "Master's", "PhD"],
    fundingType: "Fully funded",
    status: "Coming soon",
    deadlineLabel: "2027 dates not announced; 2026 ran 10 Jan–20 Feb",
    intake: "2027/28 expected",
    summary: "Flagship government scholarship combining university placement with comprehensive financial and student support.",
    eligibility: ["Nationality, age and minimum academic-achievement rules by level", "Graduated or graduating before the relevant intake", "Not currently enrolled in Türkiye at the same level applied for"],
    documents: ["Valid identity document or passport", "Recent photo, diploma and transcript", "National/international exam and language scores if required", "Research proposal and written work for PhD applicants"],
    benefits: ["University and department placement", "Tuition, monthly stipend and accommodation", "Health insurance, Turkish-language course and flight ticket"],
    steps: ["Create a free Türkiye Scholarships account", "Complete profile and programme choices", "Upload required documents", "Submit and track evaluation/interview stages"],
    officialUrl: "https://www.turkiyeburslari.gov.tr/announcements/turkiye-scholarships-2026-applications-121",
    sourceLabel: "Türkiye Scholarships",
  },
  {
    id: "tr-sabanci-ug-2026",
    name: "Sabancı University Undergraduate Scholarships",
    country: "Türkiye",
    flag: flags.Türkiye,
    provider: "Sabancı University",
    levels: ["Bachelor's"],
    fundingType: "Tuition waiver",
    status: "Open",
    deadlineLabel: "28 August 2026 · 16:00 Türkiye time",
    deadlineISO: "2026-08-28",
    intake: "2026/27",
    summary: "International undergraduate applicants are evaluated for competitive tuition scholarships through their admission file.",
    eligibility: ["International undergraduate applicant", "Meet Sabancı admission and accepted exam/diploma requirements", "Strong academic and supporting profile for scholarship consideration"],
    documents: ["Online admission application", "Secondary-school diploma and transcript", "Accepted exam/diploma result", "Passport, photo, language and other requested evidence"],
    benefits: ["Competitive tuition-waiver levels", "Scholarship decision based on the full admission file", "Conditions and duration follow the award letter"],
    steps: ["Review accepted qualifications", "Complete the international admission application", "Upload a strong and complete file before the deadline", "Receive admission and scholarship decision"],
    officialUrl: "https://iro.sabanciuniv.edu/en/application-requirements",
    sourceLabel: "Sabancı University International Relations Office",
  },
  {
    id: "tr-koc-next",
    name: "Koç University International Merit Scholarships",
    country: "Türkiye",
    flag: flags.Türkiye,
    provider: "Koç University",
    levels: ["Bachelor's", "Master's", "PhD"],
    fundingType: "Tuition waiver",
    status: "Coming soon",
    deadlineLabel: "Varies by programme and admission round",
    intake: "Next available intake",
    summary: "Merit scholarship consideration is connected to international degree admission and varies by study level and programme.",
    eligibility: ["International applicant to an eligible Koç degree", "Strong academic and admission profile", "Programme-specific eligibility for graduate funding"],
    documents: ["Complete degree admission application", "Qualifications, transcripts and test results", "Motivation, CV and references for relevant programmes", "Language proof where required"],
    benefits: ["Undergraduate tuition scholarships may range from partial to full", "Graduate packages vary by school and programme", "Award details appear in the admission offer"],
    steps: ["Choose a Koç programme", "Review its current application deadline", "Submit a complete admission file", "Check the offer for scholarship outcome and conditions"],
    officialUrl: "https://international.ku.edu.tr/scholarships/overview/",
    sourceLabel: "Koç University International Admissions",
  },
  {
    id: "tr-isdb-next",
    name: "YTB–IsDB Joint Scholarship Programme",
    country: "Türkiye",
    flag: flags.Türkiye,
    provider: "YTB and Islamic Development Bank",
    levels: ["Associate", "Bachelor's", "Master's", "PhD"],
    fundingType: "Fully funded",
    status: "Coming soon",
    deadlineLabel: "2027 dates not announced; 2026 ran 10 Jan–20 Feb",
    intake: "2027/28 expected",
    summary: "Joint scholarship route for eligible applicants from IsDB member countries and Muslim communities.",
    eligibility: ["Citizen of an eligible IsDB member country or qualifying Muslim community", "Meet Türkiye Scholarships academic and age conditions", "Programme-level and field conditions in the joint call"],
    documents: ["Identity/passport, photo, diploma and transcript", "Exam and language scores if required", "Programme choices and motivation information", "PhD research proposal where applicable"],
    benefits: ["Tuition and university placement", "Monthly stipend and accommodation", "Health insurance, Turkish-language course and flight support"],
    steps: ["Confirm country and level eligibility", "Apply through Türkiye Scholarships", "Select/indicate the joint programme where instructed", "Follow evaluation and interview messages"],
    officialUrl: "https://www.turkiyeburslari.gov.tr/announcements/ytb-islamic-development-bank-isdb-joint-scholarship-program-2026-applicaiton-period-122",
    sourceLabel: "Türkiye Scholarships / IsDB",
  },

  {
    id: "cn-schwarzman-2026",
    name: "Schwarzman Scholars 2027/28",
    country: "China",
    flag: flags.China,
    provider: "Schwarzman College, Tsinghua University",
    levels: ["Master's"],
    fundingType: "Fully funded",
    status: "Open",
    deadlineLabel: "9 September 2026 · 15:00 EDT",
    deadlineISO: "2026-09-09",
    intake: "August 2027",
    summary: "A fully funded, one-year Master of Global Affairs at Tsinghua for emerging leaders from around the world.",
    eligibility: ["Bachelor’s degree completed by 1 August 2027", "Age 18–28 on 1 August 2027", "Strong English; test waiver only under the published English-medium study rule"],
    documents: ["Online application and résumé/CV", "Essays and short-answer responses", "Academic transcripts", "Recommendation letters, video and English test where required"],
    benefits: ["Tuition, room and board", "Travel, study tour and in-country travel", "Books/supplies, health insurance and personal stipend"],
    steps: ["Use the official eligibility check", "Create the online application", "Complete essays, video and recommendations", "Submit before 15:00 EDT and prepare for interview if shortlisted"],
    officialUrl: "https://www.schwarzmanscholars.org/admissions/",
    sourceLabel: "Schwarzman Scholars Admissions",
  },
  {
    id: "cn-yenching-2027",
    name: "Yenching Academy Scholarship 2027",
    country: "China",
    flag: flags.China,
    provider: "Yenching Academy, Peking University",
    levels: ["Master's"],
    fundingType: "Fully funded",
    status: "Coming soon",
    deadlineLabel: "International cycle opens September–December 2026",
    intake: "September 2027",
    summary: "An English-taught interdisciplinary Master’s in China Studies for outstanding international candidates.",
    eligibility: ["Non-Chinese citizen with a valid passport", "Bachelor’s degree completed before enrolment", "Academic excellence, leadership potential and interest in China Studies"],
    documents: ["Online application and personal statement", "CV and official transcripts", "Degree/enrolment evidence", "Two academic references and English-language evidence"],
    benefits: ["Tuition scholarship", "Campus accommodation", "Monthly stipend, medical insurance and travel support under the award"],
    steps: ["Wait for the 2027 portal notice", "Check partner-university pre-selection if applicable", "Prepare the PKU/Yenching application and references", "Submit during the official September–December window"],
    officialUrl: "https://yenchingacademy.pku.edu.cn/ADMISSIONS.htm",
    sourceLabel: "Yenching Academy of Peking University",
  },
  {
    id: "cn-anso-next",
    name: "CAS-ANSO Scholarship",
    country: "China",
    flag: flags.China,
    provider: "Alliance of National and International Science Organizations",
    levels: ["Master's", "PhD"],
    fundingType: "Fully funded",
    status: "Coming soon",
    deadlineLabel: "2027 call not announced; previous deadline 31 January",
    intake: "2027/28 expected",
    summary: "Postgraduate science and technology scholarships at USTC or UCAS for international students.",
    eligibility: ["Non-Chinese citizen meeting USTC/UCAS admission rules", "Age and degree requirements for the selected level", "Cannot apply to both USTC and UCAS for CAS-ANSO in the same cycle"],
    documents: ["Host-university online application", "Degrees, transcripts and passport", "Study/research proposal and CV", "Referee submissions and language evidence as required"],
    benefits: ["Tuition waiver", "Monthly stipend", "Health insurance, application-fee waiver and travel support under the call"],
    steps: ["Choose either USTC or UCAS", "Select CAS-ANSO in that university application", "Submit application and referee materials", "Track university and ANSO result announcements"],
    officialUrl: "https://www.anso.org.cn/programmes/talent/scholarship/202510/t20251015_786021.html",
    sourceLabel: "CAS-ANSO official call",
  },
  {
    id: "cn-csc-next",
    name: "Chinese Government Scholarship (CSC)",
    country: "China",
    flag: flags.China,
    provider: "China Scholarship Council",
    levels: ["Bachelor's", "Master's", "PhD", "Language"],
    fundingType: "Fully funded",
    status: "Coming soon",
    deadlineLabel: "Varies by embassy, agency and university",
    intake: "2027/28 expected",
    summary: "Government scholarship routes administered through Chinese embassies, dispatching authorities and participating universities.",
    eligibility: ["Non-Chinese citizen in good health", "Degree and age criteria for the selected programme", "Meet language and university admission requirements"],
    documents: ["CSC application and passport", "Notarised qualifications and transcripts", "Study plan/research proposal and recommendations for postgraduate study", "Language, physical-exam and non-criminal-record evidence where required"],
    benefits: ["Full or partial scholarship depending on programme category", "Full awards generally cover tuition, accommodation, stipend and insurance", "Exact coverage follows the official award route"],
    steps: ["Choose the correct Type A/B route and agency number", "Check the embassy or university deadline", "Complete CampusChina and any host application", "Submit documents exactly as the nominating authority instructs"],
    officialUrl: "https://www.campuschina.org/",
    sourceLabel: "CampusChina / China Scholarship Council",
    note: "There is no single universal CSC deadline; the nominating embassy, agency or university sets it.",
  },
];

